### ISSUE TITLE
Disable VP9 decoding: Feature Request from TheGoddessInari's firefox addon

### ISSUE THREAD

**Issue by serialpotato** [jangxx/netflix-1080p#10]
Hi, I hate netflix for bitstarved 1080p VP9 encoded streams with ridiculous bitrate of 800-1000kbps. I have encountered this so many times. Like, with Witcher. And now with Lucifer series. 

But I was surprised to see there is an extension that somehow bypasses VP9 low bitrate streaming. If you were to checkout the following extension on firefox and disable the "Allow Netflix to use VP9 decoding" flag from extension/addon options, the netflix streams will in better quality. 

https://github.com/TheGoddessInari/netflix-1080p-firefox

In my case, the netflix video which was streaming at 800-1000Kbps VP9 now streamed at 3000Kbps AV1.

This is great news. I really wish this feature can be ported to chrome. I have requested the original developer for the same. Can this be done?

**Comment by serialpotato** [comment]
![11](https://user-images.githubusercontent.com/54907812/93687434-5c334d00-fad7-11ea-9b0a-aa27c9092d94.PNG)
![12](https://user-images.githubusercontent.com/54907812/93687436-60f80100-fad7-11ea-827d-a6bb2c9ec844.PNG)

The second is on chrome with this extension and the first is on firefox with Goddess extension

**Comment by serialpotato** [comment]
https://github.com/TheGoddessInari/netflix-1080p-firefox/issues/9

**Comment by jangxx** [comment]
That's a great idea! I just ported the feature from the Firefox addon and it seems to be working great. Please try out the latest version. If it works for you I'll bundle it up into a new release.

**Comment by coxackie** [comment]
cool - is there going to be a new release?

**Comment by jangxx** [comment]
Yes of course, but I'm currently waiting for serialpotato to confirm that the new changes work for them. I don't want to put out a new release only to find out something doesn't work and I have to do a new one immediately afterwards.

**Comment by serialpotato** [comment]
> That's a great idea! I just ported the feature from the Firefox addon and it seems to be working great. Please try out the latest version. If it works for you I'll bundle it up into a new release.
> 
> Edit: The feature is not enabled by default though, so you'll have to enable it in the options dialog.

Thank you! It worked. Just like firefox addon <3

**Comment by jangxx** [comment]
Interesting observation. Here in Europe, I also get low bitrate versions, but I remember Netflix and other streaming services announcing that a while ago. At least we have the option to disable it now - if Netflix ever decides to give us high bitrates again, we can simply flip the switch to reenable VP9.

Anyway, I have published a new release now, so I think we can close this issue for now.

**Comment by NovaPrima** [comment]
Any chance of also porting the similar option from the Edge version that forces AVC instead of avchigh for the same reason? It's not nearly as bad as VP9 bitrates but it can still be quite variable.

**Comment by jangxx** [comment]
I ported the feature and added an option to disable avchigh, but for me this only lead to Netflix refusing to play anything. Maybe it's because I'm on Linux or maybe it's just a Chrome - Edge difference, but I couldn't get it to work unfortunately. I already incremented the version, but I would be happy if you could try if it's working for you, before I create a new release. Otherwise I will remove it again before finalizing 1.23.0.

**Comment by NovaPrima** [comment]
Same result on Windows 7 with both Chromium and Edge unfortunately. (1.22 actually does work in Edge too; I'm not sure if an update fixed it or if there was something strange on my end.)

**Comment by jangxx** [comment]
But the AVC option from the Edge version is working for you? Well, I guess I messed something up then. I'll take a look/try again when I get around to it and until then, 1.22 will stay the latest release.

**Comment by NovaPrima** [comment]
I just tried the Edge version and it doesn't seem to go above 720p on the two shows I tried, and it also only used avchigh, so it seems it's quite broken. Anyway, working or not, thanks for your effort.

**Comment by nyuszika7h** [comment]
Yeah, if you disable avchigh it will refuse to play most titles with Widevine, it would only work in Edge with PlayReady.

**Comment by serialpotato** [comment]
https://github.com/lkmvip/netflix-4K-DDplus

The above extension also forces AVC, which has a higher bitrate than most streams. But it only works for me on the older version of Windows 10. I have just been streaming Netflix on internet explorer lately as it uses AVC by default irrespective of the Windows 10 version.
