### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Edu4rdSHL** [jangxx/netflix-1080p#11]
It isn't an issue and sorry for doing this in the issue tracker, just want to say thank you a lot for this! Keep up the good work!

**Comment by jangxx** [comment]
Thanks, I appreciate it, but as you've already pointed out, the issue tracker is not the right place for comments like this. If you want to leave an offtopic message, just send me an email; my address is linked on my profile.

**Comment by Edu4rdSHL** [comment]
Thanks, now that you know feel free to delete the "issue". 😁
