### ISSUE TITLE
sorry, this is maybe a stupid question. this is working for microsoft edge?

### ISSUE THREAD

**Issue by fahmadd** [jangxx/netflix-1080p#12]

**Comment by jangxx** [comment]
Probably not, but there is an extension that is very similar to this one, which is made to run on Edge: https://github.com/lkmvip/netflix-4K-DDplus

**Comment by NovaPrima** [comment]
At present, this extension produces Error Code: STATUS_ACCESS_VIOLATION on Edge (Dev) on Win 7.

**Comment by jangxx** [comment]
Thanks @NovaPrima for confirming that. This addon is not compatible with Edge and I'm not planning on adding support, especially since there is already an extension for Edge which does the exact same things.
