### ISSUE TITLE
Disable avchigh codec

### ISSUE THREAD

**Issue by fis60** [jangxx/netflix-1080p#13]
Hello,

Thanks for keeping this Project alive, am wondering if there is anything to do to Disable avchigh codec without breaking the playback.

Thanks

**Comment by jangxx** [comment]
Unfortunately I couldn't figure out how to make it work, yet. According to @lkmvip it works on their version of the extension in Edge, but I ported it 1:1 (as far as I can tell) and it just doesn't work for some reason. I'm still not entirely convinced that the feature is even all that necessary though. Just because the bitrates are (supposedly) higher with avchigh disabled, the picture doesn't look necessarily better, since avchigh is a more advanced codec which can squeeze a better image from fewer bits. It's entirely possible to have a higher bitrate, but worse image quality overall, so disabling avchigh might not really improve anything.

**Comment by karvai** [comment]
> Unfortunately I couldn't figure out how to make it work, yet. According to @lkmvip it works on their version of the extension in Edge, but I ported it 1:1 (as far as I can tell) and it just doesn't work for some reason. I'm still not entirely convinced that the feature is even all that necessary though. Just because the bitrates are (supposedly) higher with avchigh disabled, the picture doesn't look necessarily better, since avchigh is a more advanced codec which can squeeze a better image from fewer bits. It's entirely possible to have a higher bitrate, but worse image quality overall, so disabling avchigh might not really improve anything.

High profile has much lower bitrate comparing to Main. In most cases, Main has batter quality. Please have a look if you can do something with this to make it work. Thanks.

**Comment by Randomcoolguy123** [comment]
> Unfortunately I couldn't figure out how to make it work, yet. According to @lkmvip it works on their version of the extension in Edge, but I ported it 1:1 (as far as I can tell) and it just doesn't work for some reason. I'm still not entirely convinced that the feature is even all that necessary though. Just because the bitrates are (supposedly) higher with avchigh disabled, the picture doesn't look necessarily better, since avchigh is a more advanced codec which can squeeze a better image from fewer bits. It's entirely possible to have a higher bitrate, but worse image quality overall, so disabling avchigh might not really improve anything.

Exactly! Also most of the videos on Netflix are in AVC main profile. So if you can do something with this it'll be great help for us!

**Comment by karvai** [comment]
Hi. After some research I find that Netflix doesn't allow to stream with
with avc mpl on chrome, only chromium. Basically it's impossible. So it
would just better remove that option.

Best regards.

**Comment by jangxx** [comment]
Can you give us a bit of insight into your research @karvai? Did you look through the sources or find pieces of documentation somewhere? I'm just curious about what you found out, because when I tried researching for myself, I couldn't really find anything on the topic.

In any case, if you are sure that it is actually impossible, I would remove the feature in the next version (whenever it comes out), but I don't think that the removal of this feature warrants its own release, so the option will stick around for a bit more.

**Comment by karvai** [comment]
https://github.com/lkmvip/netflix-4K-DDplus/issues/17#issuecomment-767208834

**Comment by jangxx** [comment]
Man, I really wonder where the guy gets his information from. He always just states stuff as fact, even though I've never seen any info on how he arrives at his conclusions.

But whatever, I don't know any better as well, so I'm just going to take his word for it and remove the feature in the next version. And with that, I think we can close this issue now.

**Comment by karvai** [comment]
Check your email.

**Comment by jangxx** [comment]
Yea, I just saw it. Sounds convincing to me.

**Comment by msaifuddin** [comment]
NF encodes the higher bitrates Main profile videos on Edge using PlayReady DRM while on Chrome it uses Widevine L3, thus the lower res compared to Edge.

You can toggle PlayReady/Widevine DRM on MS Edge via the edge://flags, enable/disable one DRM at a time and check NF stream bitrates (with lkmvip/netflix-4K-DDplus extension enabled), and you can see higher bitrates are only available when you enable PlayReady DRM.

**Comment by karvai** [comment]
**msaifuddin** thanks for more detailed information about this.
Just one amendment to your statement: NF encodes the higher bitrates Main profile videos in **most of the cases**. There are exceptions when High profile has higher bitrate.

I saw series where was mixed, 1st episode was better on High and 2nd was better on Main. Main sometimes can be 2-3 times better than High.

**Comment by lkmvip** [comment]
> Man, I really wonder where the guy gets his information from. He always just states stuff as fact, even though I've never seen any info on how he arrives at his conclusions.
> 
> But whatever, I don't know any better as well, so I'm just going to take his word for it and remove the feature in the next version. And with that, I think we can close this issue now.


I think, in Netflix, 'avc code' only work on playreadyDRM ,the playreadyDRM only work on:
win10 + netflixAPP or edge (legacy) or edge (Chromium core ,must be fullinstall)

The picture is portable version EDGE(Chromium core). You can see it works in widevine and does not meet the security level "3000" required by Netflix, so it can still only stream with the highest 720P quality, and there is even no AVC code in the ESN.

![1](https://user-images.githubusercontent.com/12974141/106433295-f7d3c180-64aa-11eb-8a9f-b70a29e12c17.png)



I think, if you want to watch high-quality Netflix videos on your computer, then windows 10 and EDGE or Netflix APP may be your only choice,or Maybe you can try to fake the msl to deceive Netflix.
