### ISSUE TITLE
Higher bitrate?

### ISSUE THREAD

**Issue by madnesofjuice** [jangxx/netflix-1080p#14]
Hello! Maybe I dont know how to use it, but Im not getting the highest bitrate.
Thats the highest i get: Bit rate: 1 121 kb/s . I already checked "Automatically select best bitrate available" 
Thats from Last kids on earth s03e10

**Comment by fis60** [comment]
turn off vp9 from extension options you will get 1734
<img width="1196" alt="Screen Shot 2021-01-02 at 3 33 28 AM" src="https://user-images.githubusercontent.com/14325487/103448520-b4b7e000-4cab-11eb-969d-5865a2874eff.png">

**Comment by madnesofjuice** [comment]
Thanks, it worked.

**Comment by jangxx** [comment]
If everything is sorted out, I will close this issue now. I would also like to point out, that this repo has the new Discussions feature enabled, which is perfect for these kind of non-bugreport support questions.
