### ISSUE TITLE
AVC Codec

### ISSUE THREAD

**Issue by Tomansir** [jangxx/netflix-1080p#15]
Is it possible to get play AVC codec like this extension which play AVC codec on Microsoft edge (chromium)  https://github.com/lkmvip/netflix-4K-DDplus by tuning on all the option
![image](https://user-images.githubusercontent.com/80454296/110767772-ceb00900-8280-11eb-987c-9aa6f7492f1c.png)

If i disable both VP9 and avchigh, the streams get broken

**Comment by jangxx** [comment]
AVC is not supported on Chrome, see https://github.com/jangxx/netflix-1080p/issues/13
