### ISSUE TITLE
Using the "Next episode" feature defaults to 720p

### ISSUE THREAD

**Issue by Fanatiikon** [jangxx/netflix-1080p#18]
Watching a show each episode needs to be selected from the home page otherwise pressing "Next episode" will lock the next episode at 720p. This occurs in a different way as well that also affects movies. If the movie/episode is paused for a longer duration the quality also defaults to 720p. Refreshing the page does not fix this issue. The only fix is going back to the home page and starting the episode/movie again.

**Comment by jangxx** [comment]
That sounds very annoying. I will try to reproduce your issue and then attempt to fix it if I can reproduce it.

**Comment by Fanatiikon** [comment]
You can close this as far as i'm concerned. I realised i was still running the previous version->updated. Issue no longer occurs.(or when it did a refresh now fixed it unlike before)

**Comment by jangxx** [comment]
Okay good, thanks for the follow up.
