### ISSUE TITLE
Can't play video

### ISSUE THREAD

**Issue by silence-mfy** [jangxx/netflix-1080p#2]
If the movie does not support 1080p, it cannot be played,and report the following error.
![image](https://user-images.githubusercontent.com/57520723/83967192-e2919d80-a8f1-11ea-8a5e-da01cdd91ecd.png)

**Comment by suaksoz** [comment]
I can't watch Watchmen with this extension. Any issues?

**Comment by Problematist** [comment]
Still works for me on Chrome on Linux if you drag & drop the .crx file in Chrome. 
You'll get a pop-up on Windows every time you open Chrome so be sure to install Chrome Dev.

I only get the error when I install the extension with a source code folder.
Brave only supports this method so it might break with a few browsers.

**Comment by jangxx** [comment]
@Problematist Did you checkout the patch-1 branch when loading the unpacked extension? The master branch still contains the old version 1.19 that doesn't work anymore.

**Comment by Problematist** [comment]
@jangxx Oh, didn't notice that. Now it works. Thanks!
