### ISSUE TITLE
Bitrate menu is no longer interactable.

### ISSUE THREAD

**Issue by Fanatiikon** [jangxx/netflix-1080p#28]
The bitrate menu can be opened by pressing ctrl-alt-shift-S but it cannot be interacted with it acts as if part of the video. Clicking on it makes the video pause/play.
Edit: corrected the shortcut
Edit 2: audio tracks are also incosistent ( i have 5.1 german but only 2.0 english)(im not even german btw)

**Comment by lkmvip** [comment]
update playcore ≥ 6.0031

**Comment by jangxx** [comment]
The bitrate menu is fixed in 1.25.0.

The inconsistent audio tracks are on Netflixes end. Can't do anything about it unfortunately.
