### ISSUE TITLE
Can't manually enable extension

### ISSUE THREAD

**Issue by Hillgrove** [jangxx/netflix-1080p#32]
"This extension is not listed in the Chrome Web Store and may have been added without your knowledge."

Netflix 1080p 1.25.0.

I've used the earlier versions without problems.

**Comment by jangxx** [comment]
If you are on Windows you have to load the unpacked extension (or do some group policy stuff, but you have to google that for yourself). Just download the repo as a zip file, unpack it, head to the extension page, enable developer mode in the top right corner and then click on `Load unpacked`.

**Comment by goodffd** [comment]
it seems the latest chrome has a policy to avoid to enable the third extension which is not listed in chrome store.
