### ISSUE TITLE
cannot right click to see debug information or menu anymore

### ISSUE THREAD

**Issue by chrcoluk** [jangxx/netflix-1080p#35]
Seems the resolution is still set to 1080p, using ctrl-shift-alt-q confirms that, a very awkward combo though, shouldnt right click also bright this up?

**Comment by jangxx** [comment]
I am not aware of right-click ever bringing up the info overlay, but Ctrl+Alt+Shift+D (and apparently Ctrl+Alt+Shift+Q, didn't know that either) has always worked and continues to work.

**Comment by chrcoluk** [comment]
What about the menu that allows you to pick bitrate? Screen shots of that here on github.

**Comment by jangxx** [comment]
The bitrate menu can be opened with Ctrl+Alt+Shift+S
