### ISSUE TITLE
features, now, Netflix has provided AVC configuration for chrome

### ISSUE THREAD

**Issue by lkmvip** [jangxx/netflix-1080p#36]
WIN10 20H2  chrme v94

![sss](https://user-images.githubusercontent.com/12974141/142796569-2cf41f4a-43b4-4ae1-b5ea-4b26819d4b31.png)

**Comment by jangxx** [comment]
Does what mean we can add a "disable AVChigh" switch now?

**Comment by lkmvip** [comment]
yes

**Comment by jangxx** [comment]
Alright, thanks for the tip, version 1.26.0 has been published and the AVChigh option is back.
