### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by floh96** [jangxx/netflix-1080p#39]
fyi you need to update to manifest version 3 until the end of the year

> Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

**Comment by jangxx** [comment]
Yea I saw that, but I didn't have time to look into what that actually takes. Apparently V3 is changing the way request redirection works, so this update takes a bit more than just incrementing the version number to 3. It shouldn't be too hard but I just hadn't had the time yet and 2023 is still a ways out.

**Comment by jangxx** [comment]
Fixed in 1.27.0.
