### ISSUE TITLE
All audio/subtitle options

### ISSUE THREAD

**Issue by DorCoMaNdO** [jangxx/netflix-1080p#40]
Might be a little bit out of scope, but [lkmvip/netflix-4K-DDplus](https://github.com/lkmvip/netflix-4K-DDplus) seems to have the option to enable all audio/subtitle options, which can be useful when using a VPN to view a title that isn't available, but it does have audio/subtitle tracks (especially true if the title was previously available in other regions).
I dug around and it seems to be a very simple tweak:
https://github.com/lkmvip/netflix-4K-DDplus/blob/87fb0da3a96f4a71664987b3f94389b9cdbe3cc2/cadmium-playercore-6.0034.030.911.js#L137911-L137913
Lines 137,911 through 137,913 if this does not embed (file is large):
```js
if(useallSub) {
    E.showAllSubDubTracks = 1
}
```
For the current player in the repository it would be inserted after line 126,509, var `E` would be `G`, `useallSub` is the user's choice for enabling the feature in the extension.

**Comment by jangxx** [comment]
Good idea, I'll add this feature as soon as I get around to it (which shouldn't be in the too distant future).
