### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by HaroldWren** [jangxx/netflix-1080p#47]
Extension version: 1.28.0
Chrome version: 109.0.5414.120 & The Canary Version(Both)
Windows version: Workstation 22H2 19045.2604 & Home

I can't play netflix in 1080p but just in 960×540, and I try to use the extension in different devices and different version of Windows. Could you please check the extension? Thank you.

**Comment by jangxx** [comment]
This is a problem with Netflix's DRM that I can't do anything about unfortunately.

https://github.com/jangxx/netflix-1080p/issues/9

For titles without the stricter DRM the extension still works as intended, but for others you need to switch to Edge or the Windows Store app I'm afraid.

**Comment by upradeepk** [comment]
Do you have a proper Netflix plan that supports FullHD? If you don't have FullHD supported plan then you will not get 1080p video.
