### ISSUE TITLE
Netflix blocking on plan with ads

### ISSUE THREAD

**Issue by underailton** [jangxx/netflix-1080p#48]
Netflix keeps blocking in the plan with ads, with the extension activated it gives this error M7111-1331, it only works if I deactivate it.
On the Netflix website it says it has Full HD.

**Comment by jangxx** [comment]
I just released a new version with an updated playercore, which hopefully fixes this problem. I don't have access to a plan with ads myself, so I can't test it unfortunately.

**Comment by underailton** [comment]
Apparently it has been fixed, there is no more error message and it is in 1080p, thanks.

**Comment by jangxx** [comment]
Perfect, that's great to hear.
