### ISSUE TITLE
error UI3013 from 2024-03-20

### ISSUE THREAD

**Issue by dmfr** [jangxx/netflix-1080p#49]
Hi,

Extension stopped working on 2024-03-20, as same with (older) truedread.
Shows error UI3013
Disabling extension restores playback, capped to 720p.

Thanks for the work so far & regards !

**Comment by serialpotato** [comment]
> Hi,
> 
> Extension stopped working on 2024-03-20, as same with (older) truedread. Shows error UI3013 Disabling extension restores playback, capped to 720p.
> 
> Thanks for the work so far & regards !

https://github.com/DavidBuchanan314/Turbo-Recadmiumator 

You can use the above one, but it doesn't have AVC, prk configuration which is needed for higher bitrate. The famous netflix 4k addon has that, but it is also suffering the same fate. Looks like the playercore needs to be updated.

**Comment by dmfr** [comment]
Thanks for the quick response,
Turbo-Recadmiumator does restore 1080p playback at good (subjective) quality.
Have no hardware for higher resolution so i can't say more.

Thanks a lot again !

**Comment by jangxx** [comment]
Thanks for the report. I just released version 1.30.0 of the extension which should fix your problem.

**Comment by dmfr** [comment]
Thanks a lot for the quick update !!
Confirmed that it works fine now.
