### ISSUE TITLE
I can't get it to start

### ISSUE THREAD

**Issue by MikiIsAway** [jangxx/netflix-1080p#5]
Since Chrome only lets me launch apps that are available in the Chrome App Store I can't get this app to start. Is there any way to circumvent this?

**Comment by TobySkarting** [comment]
google

**Comment by MikiIsAway** [comment]
> google

so you think before I made an extra account just for this on this website and wrote this comment here I haven't actually tried that yet

**Comment by dominoto** [comment]
> > google
> 
> so you think before I made an extra account just for this on this website and wrote this comment here I haven't actually tried that yet

Your Google-fu is weak, grasshopper. Here is an easy-to-follow video guide: https://youtu.be/GUH4SKumc80

**Comment by jangxx** [comment]
Installation instructions have been added to the readme some time ago, so I think we can close this now.
