### ISSUE TITLE
@jangxx  now, chrome can play 4K

### ISSUE THREAD

**Issue by lkmvip** [jangxx/netflix-1080p#53]
@jangxx 

now, chrome can play 4K
my os win11,chrome 124.0.6367.61 fullinstall

other information:
https://help.netflix.com/node/23931

enjoy

**Comment by jangxx** [comment]
That's awesome! Only problem is I'm not paying for Netflix 4K and I also rarely ever use Windows so this is going to be hard to test.

**Comment by lkmvip** [comment]
> That's awesome! Only problem is I'm not paying for Netflix 4K and I also rarely ever use Windows so this is going to be hard to test.

oops :smile:
