### ISSUE TITLE
Extension breaks some shows

### ISSUE THREAD

**Issue by sn-o-w** [jangxx/netflix-1080p#56]
Hi.

I'm trying to watch this: https://www.netflix.com/watch/81764952

But it looks like I get this error:
![](https://github.com/user-attachments/assets/1220c11d-56be-448e-bd2c-9eb06a916d4c)

Disabling the extension will allow me to watch the above URL. 🤔

**Comment by jangxx** [comment]
Thanks for the report, I'll look into it tomorrow or so. Probably just needs an update for the playercore again.

**Comment by jangxx** [comment]
I just fixed the issue and published version 1.31.4 to the Release page and submitted it for review on the Chrome Webstore. You can download the version from Github if you need it right away or wait for a few days until it has cleared the review on the Webstore.
